// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateTextbookTextbooksPostData, CreateTextbookTextbooksPostErrors, CreateTextbookTextbooksPostResponses, CreateUserUsersPostData, CreateUserUsersPostErrors, CreateUserUsersPostResponses, DeleteTextbookTextbooksTextbookIdDeleteData, DeleteTextbookTextbooksTextbookIdDeleteErrors, DeleteTextbookTextbooksTextbookIdDeleteResponses, DeleteUserUsersUserIdDeleteData, DeleteUserUsersUserIdDeleteErrors, DeleteUserUsersUserIdDeleteResponses, HealthCheckHealthGetData, HealthCheckHealthGetResponses, ListTextbooksTextbooksGetData, ListTextbooksTextbooksGetResponses, ListUsersUsersGetData, ListUsersUsersGetResponses, LoginAuthLoginPostData, LoginAuthLoginPostErrors, LoginAuthLoginPostResponses, ReadCurrentUserAuthMeGetData, ReadCurrentUserAuthMeGetResponses, ReadRootGetData, ReadRootGetResponses, ResetUserPasswordUsersUserIdResetPasswordPostData, ResetUserPasswordUsersUserIdResetPasswordPostErrors, ResetUserPasswordUsersUserIdResetPasswordPostResponses, UpdateTextbookTextbooksTextbookIdPutData, UpdateTextbookTextbooksTextbookIdPutErrors, UpdateTextbookTextbooksTextbookIdPutResponses, UpdateUserUsersUserIdPutData, UpdateUserUsersUserIdPutErrors, UpdateUserUsersUserIdPutResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Users
 */
export const listUsersUsersGet = <ThrowOnError extends boolean = false>(options?: Options<ListUsersUsersGetData, ThrowOnError>) => (options?.client ?? client).get<ListUsersUsersGetResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users',
    ...options
});

/**
 * Create User
 */
export const createUserUsersPost = <ThrowOnError extends boolean = false>(options: Options<CreateUserUsersPostData, ThrowOnError>) => (options.client ?? client).post<CreateUserUsersPostResponses, CreateUserUsersPostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete User
 */
export const deleteUserUsersUserIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteUserUsersUserIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteUserUsersUserIdDeleteResponses, DeleteUserUsersUserIdDeleteErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{user_id}',
    ...options
});

/**
 * Update User
 */
export const updateUserUsersUserIdPut = <ThrowOnError extends boolean = false>(options: Options<UpdateUserUsersUserIdPutData, ThrowOnError>) => (options.client ?? client).put<UpdateUserUsersUserIdPutResponses, UpdateUserUsersUserIdPutErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{user_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reset User Password
 */
export const resetUserPasswordUsersUserIdResetPasswordPost = <ThrowOnError extends boolean = false>(options: Options<ResetUserPasswordUsersUserIdResetPasswordPostData, ThrowOnError>) => (options.client ?? client).post<ResetUserPasswordUsersUserIdResetPasswordPostResponses, ResetUserPasswordUsersUserIdResetPasswordPostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{user_id}/reset-password',
    ...options
});

/**
 * List Textbooks
 */
export const listTextbooksTextbooksGet = <ThrowOnError extends boolean = false>(options?: Options<ListTextbooksTextbooksGetData, ThrowOnError>) => (options?.client ?? client).get<ListTextbooksTextbooksGetResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/textbooks',
    ...options
});

/**
 * Create Textbook
 */
export const createTextbookTextbooksPost = <ThrowOnError extends boolean = false>(options: Options<CreateTextbookTextbooksPostData, ThrowOnError>) => (options.client ?? client).post<CreateTextbookTextbooksPostResponses, CreateTextbookTextbooksPostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/textbooks',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Textbook
 */
export const deleteTextbookTextbooksTextbookIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteTextbookTextbooksTextbookIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteTextbookTextbooksTextbookIdDeleteResponses, DeleteTextbookTextbooksTextbookIdDeleteErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/textbooks/{textbook_id}',
    ...options
});

/**
 * Update Textbook
 */
export const updateTextbookTextbooksTextbookIdPut = <ThrowOnError extends boolean = false>(options: Options<UpdateTextbookTextbooksTextbookIdPutData, ThrowOnError>) => (options.client ?? client).put<UpdateTextbookTextbooksTextbookIdPutResponses, UpdateTextbookTextbooksTextbookIdPutErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/textbooks/{textbook_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Root
 */
export const readRootGet = <ThrowOnError extends boolean = false>(options?: Options<ReadRootGetData, ThrowOnError>) => (options?.client ?? client).get<ReadRootGetResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Login
 */
export const loginAuthLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginAuthLoginPostData, ThrowOnError>) => (options.client ?? client).post<LoginAuthLoginPostResponses, LoginAuthLoginPostErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Current User
 */
export const readCurrentUserAuthMeGet = <ThrowOnError extends boolean = false>(options?: Options<ReadCurrentUserAuthMeGetData, ThrowOnError>) => (options?.client ?? client).get<ReadCurrentUserAuthMeGetResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/me',
    ...options
});
