// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};

/**
 * ArticleCreate
 */
export type ArticleCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content?: string;
};

/**
 * ArticlePublic
 */
export type ArticlePublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Textbook Id
     */
    textbook_id: string;
    /**
     * Audio Url
     */
    audio_url?: string;
    /**
     * Sentences
     */
    sentences?: Array<ArticleSentence>;
};

/**
 * ArticleSentence
 */
export type ArticleSentence = {
    /**
     * Content
     */
    content: string;
    /**
     * Audio Url
     */
    audio_url?: string;
};

/**
 * ArticleUpdate
 */
export type ArticleUpdate = {
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content?: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    user: UserPublic;
};

/**
 * ResetPasswordResponse
 */
export type ResetPasswordResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * SystemSettingsPublic
 */
export type SystemSettingsPublic = {
    /**
     * Default Password
     */
    default_password: string;
    /**
     * Edge Tts Rate
     */
    edge_tts_rate: number;
};

/**
 * SystemSettingsUpdate
 */
export type SystemSettingsUpdate = {
    /**
     * Default Password
     */
    default_password: string;
    /**
     * Edge Tts Rate
     */
    edge_tts_rate: number;
};

/**
 * TextbookCreate
 */
export type TextbookCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * TextbookPublic
 */
export type TextbookPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * TextbookUpdate
 */
export type TextbookUpdate = {
    /**
     * Name
     */
    name: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * User Type
     */
    user_type: number;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * User Type
     */
    user_type: number;
    /**
     * User Type Description
     */
    user_type_description: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Username
     */
    username: string;
    /**
     * User Type
     */
    user_type: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type DeleteArticleArticlesArticleIdDeleteData = {
    body?: never;
    path: {
        /**
         * Article Id
         */
        article_id: string;
    };
    query?: never;
    url: '/articles/{article_id}';
};

export type DeleteArticleArticlesArticleIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteArticleArticlesArticleIdDeleteError = DeleteArticleArticlesArticleIdDeleteErrors[keyof DeleteArticleArticlesArticleIdDeleteErrors];

export type DeleteArticleArticlesArticleIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteArticleArticlesArticleIdDeleteResponse = DeleteArticleArticlesArticleIdDeleteResponses[keyof DeleteArticleArticlesArticleIdDeleteResponses];

export type UpdateArticleArticlesArticleIdPutData = {
    body: ArticleUpdate;
    path: {
        /**
         * Article Id
         */
        article_id: string;
    };
    query?: never;
    url: '/articles/{article_id}';
};

export type UpdateArticleArticlesArticleIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateArticleArticlesArticleIdPutError = UpdateArticleArticlesArticleIdPutErrors[keyof UpdateArticleArticlesArticleIdPutErrors];

export type UpdateArticleArticlesArticleIdPutResponses = {
    /**
     * Successful Response
     */
    200: ArticlePublic;
};

export type UpdateArticleArticlesArticleIdPutResponse = UpdateArticleArticlesArticleIdPutResponses[keyof UpdateArticleArticlesArticleIdPutResponses];

export type ListUsersUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type ListUsersUsersGetResponses = {
    /**
     * Response List Users Users Get
     *
     * Successful Response
     */
    200: Array<UserPublic>;
};

export type ListUsersUsersGetResponse = ListUsersUsersGetResponses[keyof ListUsersUsersGetResponses];

export type CreateUserUsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/users';
};

export type CreateUserUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserUsersPostError = CreateUserUsersPostErrors[keyof CreateUserUsersPostErrors];

export type CreateUserUsersPostResponses = {
    /**
     * Successful Response
     */
    201: UserPublic;
};

export type CreateUserUsersPostResponse = CreateUserUsersPostResponses[keyof CreateUserUsersPostResponses];

export type DeleteUserUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type DeleteUserUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserUsersUserIdDeleteError = DeleteUserUsersUserIdDeleteErrors[keyof DeleteUserUsersUserIdDeleteErrors];

export type DeleteUserUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserUsersUserIdDeleteResponse = DeleteUserUsersUserIdDeleteResponses[keyof DeleteUserUsersUserIdDeleteResponses];

export type UpdateUserUsersUserIdPutData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type UpdateUserUsersUserIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserUsersUserIdPutError = UpdateUserUsersUserIdPutErrors[keyof UpdateUserUsersUserIdPutErrors];

export type UpdateUserUsersUserIdPutResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UpdateUserUsersUserIdPutResponse = UpdateUserUsersUserIdPutResponses[keyof UpdateUserUsersUserIdPutResponses];

export type ResetUserPasswordUsersUserIdResetPasswordPostData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}/reset-password';
};

export type ResetUserPasswordUsersUserIdResetPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetUserPasswordUsersUserIdResetPasswordPostError = ResetUserPasswordUsersUserIdResetPasswordPostErrors[keyof ResetUserPasswordUsersUserIdResetPasswordPostErrors];

export type ResetUserPasswordUsersUserIdResetPasswordPostResponses = {
    /**
     * Successful Response
     */
    200: ResetPasswordResponse;
};

export type ResetUserPasswordUsersUserIdResetPasswordPostResponse = ResetUserPasswordUsersUserIdResetPasswordPostResponses[keyof ResetUserPasswordUsersUserIdResetPasswordPostResponses];

export type ListTextbooksTextbooksGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/textbooks';
};

export type ListTextbooksTextbooksGetResponses = {
    /**
     * Response List Textbooks Textbooks Get
     *
     * Successful Response
     */
    200: Array<TextbookPublic>;
};

export type ListTextbooksTextbooksGetResponse = ListTextbooksTextbooksGetResponses[keyof ListTextbooksTextbooksGetResponses];

export type CreateTextbookTextbooksPostData = {
    body: TextbookCreate;
    path?: never;
    query?: never;
    url: '/textbooks';
};

export type CreateTextbookTextbooksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTextbookTextbooksPostError = CreateTextbookTextbooksPostErrors[keyof CreateTextbookTextbooksPostErrors];

export type CreateTextbookTextbooksPostResponses = {
    /**
     * Successful Response
     */
    201: TextbookPublic;
};

export type CreateTextbookTextbooksPostResponse = CreateTextbookTextbooksPostResponses[keyof CreateTextbookTextbooksPostResponses];

export type DeleteTextbookTextbooksTextbookIdDeleteData = {
    body?: never;
    path: {
        /**
         * Textbook Id
         */
        textbook_id: string;
    };
    query?: never;
    url: '/textbooks/{textbook_id}';
};

export type DeleteTextbookTextbooksTextbookIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTextbookTextbooksTextbookIdDeleteError = DeleteTextbookTextbooksTextbookIdDeleteErrors[keyof DeleteTextbookTextbooksTextbookIdDeleteErrors];

export type DeleteTextbookTextbooksTextbookIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTextbookTextbooksTextbookIdDeleteResponse = DeleteTextbookTextbooksTextbookIdDeleteResponses[keyof DeleteTextbookTextbooksTextbookIdDeleteResponses];

export type UpdateTextbookTextbooksTextbookIdPutData = {
    body: TextbookUpdate;
    path: {
        /**
         * Textbook Id
         */
        textbook_id: string;
    };
    query?: never;
    url: '/textbooks/{textbook_id}';
};

export type UpdateTextbookTextbooksTextbookIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTextbookTextbooksTextbookIdPutError = UpdateTextbookTextbooksTextbookIdPutErrors[keyof UpdateTextbookTextbooksTextbookIdPutErrors];

export type UpdateTextbookTextbooksTextbookIdPutResponses = {
    /**
     * Successful Response
     */
    200: TextbookPublic;
};

export type UpdateTextbookTextbooksTextbookIdPutResponse = UpdateTextbookTextbooksTextbookIdPutResponses[keyof UpdateTextbookTextbooksTextbookIdPutResponses];

export type ListTextbookArticlesTextbooksTextbookIdArticlesGetData = {
    body?: never;
    path: {
        /**
         * Textbook Id
         */
        textbook_id: string;
    };
    query?: never;
    url: '/textbooks/{textbook_id}/articles';
};

export type ListTextbookArticlesTextbooksTextbookIdArticlesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTextbookArticlesTextbooksTextbookIdArticlesGetError = ListTextbookArticlesTextbooksTextbookIdArticlesGetErrors[keyof ListTextbookArticlesTextbooksTextbookIdArticlesGetErrors];

export type ListTextbookArticlesTextbooksTextbookIdArticlesGetResponses = {
    /**
     * Response List Textbook Articles Textbooks  Textbook Id  Articles Get
     *
     * Successful Response
     */
    200: Array<ArticlePublic>;
};

export type ListTextbookArticlesTextbooksTextbookIdArticlesGetResponse = ListTextbookArticlesTextbooksTextbookIdArticlesGetResponses[keyof ListTextbookArticlesTextbooksTextbookIdArticlesGetResponses];

export type CreateTextbookArticleTextbooksTextbookIdArticlesPostData = {
    body: ArticleCreate;
    path: {
        /**
         * Textbook Id
         */
        textbook_id: string;
    };
    query?: never;
    url: '/textbooks/{textbook_id}/articles';
};

export type CreateTextbookArticleTextbooksTextbookIdArticlesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTextbookArticleTextbooksTextbookIdArticlesPostError = CreateTextbookArticleTextbooksTextbookIdArticlesPostErrors[keyof CreateTextbookArticleTextbooksTextbookIdArticlesPostErrors];

export type CreateTextbookArticleTextbooksTextbookIdArticlesPostResponses = {
    /**
     * Successful Response
     */
    201: ArticlePublic;
};

export type CreateTextbookArticleTextbooksTextbookIdArticlesPostResponse = CreateTextbookArticleTextbooksTextbookIdArticlesPostResponses[keyof CreateTextbookArticleTextbooksTextbookIdArticlesPostResponses];

export type ReadSystemSettingsSystemSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system-settings';
};

export type ReadSystemSettingsSystemSettingsGetResponses = {
    /**
     * Successful Response
     */
    200: SystemSettingsPublic;
};

export type ReadSystemSettingsSystemSettingsGetResponse = ReadSystemSettingsSystemSettingsGetResponses[keyof ReadSystemSettingsSystemSettingsGetResponses];

export type SaveSystemSettingsSystemSettingsPutData = {
    body: SystemSettingsUpdate;
    path?: never;
    query?: never;
    url: '/system-settings';
};

export type SaveSystemSettingsSystemSettingsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaveSystemSettingsSystemSettingsPutError = SaveSystemSettingsSystemSettingsPutErrors[keyof SaveSystemSettingsSystemSettingsPutErrors];

export type SaveSystemSettingsSystemSettingsPutResponses = {
    /**
     * Successful Response
     */
    200: SystemSettingsPublic;
};

export type SaveSystemSettingsSystemSettingsPutResponse = SaveSystemSettingsSystemSettingsPutResponses[keyof SaveSystemSettingsSystemSettingsPutResponses];

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Response Read Root  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type ReadRootGetResponse = ReadRootGetResponses[keyof ReadRootGetResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Response Health Check Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthCheckHealthGetResponse = HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses];

export type LoginAuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAuthLoginPostError = LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: LoginResponse;
};

export type LoginAuthLoginPostResponse = LoginAuthLoginPostResponses[keyof LoginAuthLoginPostResponses];

export type ReadCurrentUserAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type ReadCurrentUserAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type ReadCurrentUserAuthMeGetResponse = ReadCurrentUserAuthMeGetResponses[keyof ReadCurrentUserAuthMeGetResponses];
